server:
  port: 8083
spring:
  application:
    name: product
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/desafio?allowPublicKeyRetrieval=true&sslMode=DISABLED&Timezone=true&serverTimezone=UTC
    username: root
    password:
jwt:
  config:
    type: signed
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
